In [1]:
import pandas as pd 
import numpy as np

In [9]:
df = pd.read_excel(r"C:\Users\chakradhar\cardekho\chennai_cars.xlsx")

In [10]:
df.head()

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Minivans', 'k...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...

In [11]:
import ast

# Function to convert string representations of dictionaries into actual dictionaries
def convert_to_dict(column):
    return column.apply(lambda x: ast.literal_eval(str(x)) if isinstance(x, str) else x)

# Convert relevant columns to dictionaries
df['new_car_detail'] = convert_to_dict(df['new_car_detail'])
df['new_car_overview'] = convert_to_dict(df['new_car_overview'])
df['new_car_feature'] = convert_to_dict(df['new_car_feature'])
df['new_car_specs'] = convert_to_dict(df['new_car_specs'])

# Extracting relevant details from the nested columns
df_extracted = pd.DataFrame()

# Extract details from 'new_car_detail'
df_extracted['fuel_type'] = df['new_car_detail'].apply(lambda x: x.get('ft') if isinstance(x, dict) else None)
df_extracted['body_type'] = df['new_car_detail'].apply(lambda x: x.get('bt') if isinstance(x, dict) else None)
df_extracted['km_driven'] = df['new_car_detail'].apply(lambda x: x.get('km') if isinstance(x, dict) else None)

# Extract details from 'new_car_overview'
df_extracted['registration_year'] = df['new_car_overview'].apply(lambda x: x.get('top')[0]['value'] if isinstance(x, dict) and 'top' in x else None)

# Add the city column
df_extracted['City'] = 'Chennai'

# Display the structured data
df_extracted.head()

  fuel_type  body_type km_driven registration_year     City
0    Petrol        SUV    20,000              2022  Chennai
1    Petrol   Minivans    20,687          Feb 2015  Chennai
2    Petrol        SUV    30,000              2021  Chennai
3    Petrol  Hatchback    59,247          May 2015  Chennai
4    Petrol  Hatchback    50,000              2015  Chennai

In [12]:
# Extracting additional fields from 'new_car_detail'
df_extracted['owner_type'] = df['new_car_detail'].apply(lambda x: x.get('ot') if isinstance(x, dict) else None)
df_extracted['insurance_type'] = df['new_car_detail'].apply(lambda x: x.get('it') if isinstance(x, dict) else None)

# Extracting additional fields from 'new_car_overview'
df_extracted['make_model'] = df['new_car_overview'].apply(lambda x: x.get('top')[1]['value'] if isinstance(x, dict) and len(x.get('top', [])) > 1 else None)

# Extract details from 'new_car_feature' (assuming top-level keys like 'value' describe features)
df_extracted['features'] = df['new_car_feature'].apply(lambda x: ', '.join([f['value'] for f in x.get('top', [])]) if isinstance(x, dict) else None)

# Extract details from 'new_car_specs' (e.g., engine type, transmission, etc.)
df_extracted['engine_type'] = df['new_car_specs'].apply(lambda x: x.get('top')[0]['value'] if isinstance(x, dict) and 'top' in x else None)
df_extracted['transmission'] = df['new_car_specs'].apply(lambda x: x.get('top')[1]['value'] if isinstance(x, dict) and len(x.get('top', [])) > 1 else None)

# Retain the car links
df_extracted['car_links'] = df['car_links']

# Display the updated structured data
df_extracted.head()

,fuel_type,body_type,km_driven,registration_year,City,owner_type,insurance_type,make_model,features,engine_type,transmission,car_links
0,Petrol,SUV,"20,000",2022,Chennai,None,0,Third Party insurance,"Power Steering, Power Windows Front, Air Condi...",998 CC,118.36bhp,https://www.cardekho.com/used-car-details/used...
1,Petrol,Minivans,"20,687",Feb 2015,Chennai,None,0,Comprehensive,"Low Fuel Warning Light, Accessory Power Outlet...",15.37 kmpl,1196 CC,https://www.cardekho.com/buy-used-car-details/...
2,Petrol,SUV,"30,000",2021,Chennai,None,0,Third Party insurance,"Power Steering, Power Windows Front, Air Condi...",20 kmpl,999 CC,https://www.cardekho.com/used-car-details/used...
3,Petrol,Hatchback,"59,247",May 2015,Chennai,None,0,Comprehensive,"Power Steering, Power Windows Front, Air Condi...",19.81 kmpl,1086 CC,https://www.cardekho.com/buy-used-car-details/...
4,Petrol,Hatchback,"50,000",2015,Chennai,None,0,Third Party insurance,"Power Steering, Power Windows Front, Air Condi...",18.7 kmpl,1199 CC,https://www.cardekho.com/used-car-details/used...